version: "3.9"
services:

  service-discovery:
    image: service-discovery
    ports:
      - 9999:9999
    environment:
      - EUREKA_SERVER=http://service-discovery:9999/eureka
    volumes:
      - ../.:/DockerWorkspace
    networks:
      - myNetwork

  configuration-server:
    image: configuration-server
    ports:
      - 8881:8881
    environment:
      - EUREKA_SERVER=http://service-discovery:9999/eureka
    volumes:
      - type: bind
        source: ../.
        target: /DockerWorkspace
    networks:
      - myNetwork
    depends_on:
      - service-discovery

  limits-service:
    image: limits-service
    ports:
      - 7071:7071
    environment:
      - EUREKA_SERVER=http://service-discovery:9999/eureka
      - CONFIGURATION_SERVER_URL=http://configuration-server:8881
    volumes:
      - ../.:/DockerWorkspace
    networks:
      - myNetwork
    depends_on:
      - service-discovery
      - configuration-server
    #entrypoint: ["/DockerWorkspace/wait-for-it.sh" , "configuration-server:8881" , "--strict" , "--timeout=60" , "--" , "java","-jar","/DockerWorkspace/limits-service/target/limits-service-0.0.1-SNAPSHOT.jar"]
    entrypoint: ["/DockerWorkspace/limits-service/wait-and-run.sh","2m","./DockerWorkspace/limits-service/target/limits-service-0.0.1-SNAPSHOT.jar"]

  currency-exchange:
    image: currency-exchange
    ports:
      - 9091
    environment:
      - EUREKA_SERVER=http://service-discovery:9999/eureka
    volumes:
      - type: bind
        source: ../.
        target: /DockerWorkspace
    networks:
      - myNetwork
    depends_on:
      - service-discovery

  currency-calculation:
    image: currency-calculation
    ports:
      - 8081:8081
    environment:
      - EUREKA_SERVER=http://service-discovery:9999/eureka
    volumes:
      - type: bind
        source: ../.
        target: /DockerWorkspace
    networks:
      - myNetwork
    depends_on:
      - service-discovery

  api-gateway:
    image: api-gateway
    ports:
      - 8080:8080
    environment:
      - EUREKA_SERVER=http://service-discovery:9999/eureka
    volumes:
      - type: bind
        source: ../.
        target: /DockerWorkspace
    networks:
      - myNetwork
    depends_on:
      - service-discovery

networks:
  myNetwork:
    driver: bridge

